FROM php:8.1-apache

COPY . /app

RUN apt-get update && apt-get install -y

WORKDIR /app

COPY .env .

EXPOSE 9011

CMD ["php", "artisan", "config:cache", "&&", "php", "artisan", "serve", "--host=0.0.0.0", "--port=9011"]
