version: "3.9"  # (Optional)

services:
  backend:
    restart: unless-stopped
    container_name: 'backend'
    build:
      context: ./Back  # Assuming a typo here, correct to "Back" (build context)
      dockerfile: Dockerfile_back  # Path to Dockerfile within context
    links:
      - db
    ports:
      - "0.0.0.0:8000:8011"

  frontend:
    restart: unless-stopped
    container_name: 'front'
    build:
      context: ./front  # Build context for frontend service
      dockerfile: Dockerfile_front  # Path to Dockerfile within context
    links:
      - db
    ports:
      - "0.0.0.0:9000:9011"

  db:
    restart: always
    container_name: 'db_mysql2'
    build: ./db/Dockerfile_mysql
    environment:
      MYSQL_DATABASE: 'yacyreta'
      MYSQL_USER: 'yacyreta'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_vol:/var/lib/mysql

volumes:
  db_vol:


